### ISSUE TITLE
Site CSS doesn't load because it's not set up for HTTPS

### ISSUE THREAD

**Issue by wslack** [ombegov/a130#137]
@mattbailey0, are you the right person?

**Comment by MatthewFordKern** [comment]
No.

 

 

Matthew Ford Kern 

MSEA BSEE CEA(FEAF) CEA(DODAF) CEA(Zachman) CISSP-ISSAP PMP ITIL

 <http://www.mkern.com/> www.mkern.com

(703) 594-6852

**Comment by mattbailey0** [comment]
@wslack Um, actually yes.  @MatthewFordKern you probably got an alert because you're subscribed to this thread.

**Comment by MatthewFordKern** [comment]
The question of “is this me” has the unambiguous answer “NO”.  Better articulated questions get better answers.

**Comment by mattbailey0** [comment]
Resolved!  Thanks for your perspicuity and patience @wslack
