### ISSUE TITLE
Make `gh-pages` the default branch, delete `master`

### ISSUE THREAD

**Issue by benbalter** [ombegov/a130#2]
If pull requests should be submitted to the `gh-pages` branch, and that's where development will occur,  you should set that branch as the default branch and delete `master` to A) prevent the two from getting out of sync and B) make it easier for users to properly submit pull requests both based on and to the appropriate branch.

**Comment by gbinal** [comment]
+1

**Comment by rebeccawilliams** [comment]
Updated!
