### ISSUE TITLE
Describe what's changed in the new A-130

### ISSUE THREAD

**Issue by konklone** [ombegov/a130#6]
This site houses the new version of A-130, in HTML, and PDF form, but I don't see anywhere where I can read about what's changed. The best source of this would be an official source. It doesn't need to be a fancy git diff -- a human description of the changes would be just fine.

**Comment by konklone** [comment]
Ah -- it looks like [the PDF version](https://ombegov.github.io/a130/Proposed%20A-130%20for%20Public%20Comment.pdf) has additional detail, on pages 2-4?

It looks like earlier versions of this repo had an HTML version of this section on the homepage, and there was an "Introduction" tab that had some similar information to what is now the homepage.

![image](https://cloud.githubusercontent.com/assets/4592/10646521/7132ecbe-7801-11e5-9104-c911ea5a8573.png)

Can the diff section be restored to the web version of the repo? It'd be easier to link to and expect people to read, and should improve public engagement on this process.

**Comment by jlberryhill** [comment]
Thanks, @konklone. Agreed that we should pull in some details on what's changed. @justgrimes and I will add this tomorrow.

**Comment by rebeccawilliams** [comment]
This was addressed in #12, thank you for the suggestion!
